#!/bin/zsh

__fzf::widget::init 'cd --' || return 1

tmsu files --directory $(
	tmsu tags | \
	__fzf::widget::select $FZF_WIDGET_OPTS[tmsu-change-dir] +m
  ) | \
  __fzf::widget::select $FZF_WIDGET_OPTS[tmsu-change-dir] +m | \
  __fzf::widget::insert -q

__fzf::widget::exec
