#!/bin/zsh

__fzf::widget::init 'cd --' || return 1

tag=$(tmsu tags | \
	__fzf::widget::select $FZF_WIDGET_OPTS[tmsu-change-dir] +m)

tmsu files --directory $tag | \
  __fzf::widget::select $FZF_WIDGET_OPTS[tmsu-change-dir] +m | \
  __fzf::widget::insert -q

__fzf::widget::exec
